[project]
name = "ecg-tokenizer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "evaluate>=0.4.3",
    "fastparquet>=2024.11.0",
    "iterative-stratification>=0.1.9",
    "matplotlib>=3.9.2",
    "pandas>=2.2.3",
    "pyarrow>=19.0.0",
    "rouge-score>=0.1.2",
    "scikit-learn>=1.5.2",
    "torch>=2.4.1",
    "tqdm>=4.66.5",
    "transformers>=4.46.2",
    "vector-quantize-pytorch>=1.21.8",
    "wandb>=0.18.3",
]
