# pipeline project
pipeline_project: !!str "ECG_Tokenizer_Training"
output_dir: !!str "checkpoints"
run_mode: !!str "train"
num_epochs: !!int 1
seed: !!int 42
# wandb parameters
wandb_project: !!str "ECG_Tokenizer_Training"
wandb_entity: !!str "jacques-delfrate"
use_wandb: !!bool false
# training parameters
lr: !!float 3e-4
scheduler_name: !!str "step"
lr_step_period: !!int 1
factor: !!float 0.3
optimizer: !!str "AdamW"
weight_decay: !!float 1e-4
step_size: !!int 1
gamma: !!float 0.1
use_amp: !!bool true
# VQVAE parameters
num_quantizers: !!int 8
num_codes: !!int 1024
# Dataset parameters
train_dataset_path: !!str "parquets/mimic_mhi/mimic_mhi_train.parquet"
validation_dataset_path: !!str "parquets/mimic/mimic_v4_clean_test.parquet"
num_workers: !!int 12
batch_size: !!int 32
# waveform parameters
waveform_length: !!int 2500
num_leads: !!int 12
