import os
from enum import Enum

standard_lead_order = ["I", 
    "II", 
    "III", 
    "aVR", 
    "aVL", 
    "aVF", 
    "V1", 
    "V2", 
    "V3", 
    "V4", 
    "V5", 
    "V6"
]
lead_to_idx = {lead: idx for idx, lead in enumerate(standard_lead_order)}


ECG_PATTERNS = {
    "Sinusal": "Rythme sinusal normal",
    "Regular": "Rythme régulier",
    "Monomorph": "Monomorphe",
    "QS complex in V1-V2-V3": "Complexe QS dans les dérivations V1-V2-V3",
    "R complex in V5-V6": "Complexe R dans les dérivations V5-V6",
    "T wave inversion (inferior - II, III, aVF)": "Inversion de l'onde T dans les dérivations inférieures (II, III, aVF)",
    "Left bundle branch block": "Bloc de branche gauche",
    "RaVL > 11 mm": "RaVL > 11 mm",
    "SV1 + RV5 or RV6 > 35 mm": "SV1 + RV5 ou RV6 > 35 mm",
    "T wave inversion (lateral -I, aVL, V5-V6)": "Inversion de l'onde T dans les dérivations latérales (I, aVL, V5-V6)",
    "T wave inversion (anterior - V3-V4)": "Inversion de l'onde T dans les dérivations antérieures (V3-V4)",
    "Left axis deviation": "Déviation de l'axe gauche",
    "Left ventricular hypertrophy": "Hypertrophie ventriculaire gauche",
    "Bradycardia": "Bradycardie",
    "Q wave (inferior - II, III, aVF)": "Onde Q dans les dérivations inférieures (II, III, aVF)",
    "Afib": "Fibrillation auriculaire",
    "Irregularly irregular": "Rythme irrégulierement irrégulier",
    "Atrial tachycardia (>= 100 BPM)": "Tachycardie atriale (≥ 100 BPM)",
    "Nonspecific intraventricular conduction delay": "Retard de conduction intraventriculaire non spécifique",
    "Premature ventricular complex": "Complexe ventriculaire prématuré",
    "Polymorph": "Polymorphe",
    "T wave inversion (septal- V1-V2)": "Inversion de l'onde T dans les dérivations septales (V1-V2)",
    "Right bundle branch block": "Bloc de branche droit",
    "Ventricular paced": "Rythme ventriculaire électro-entraîné",
    "ST elevation (anterior - V3-V4)": "Élévation du segment ST dans les dérivations antérieures (V3-V4)",
    "ST elevation (septal - V1-V2)": "Élévation du segment ST dans les dérivations septales (V1-V2)",
    "1st degree AV block": "Bloc auriculo-ventriculaire du premier degré",
    "Premature atrial complex": "Complexe auriculaire prématuré",
    "Atrial flutter": "Flutter auriculaire",
    "rSR' in V1-V2": "rSR dans les dérivations V1-V2",
    "qRS in V5-V6-I, aVL": "qRS dans les dérivations V5-V6-I, aVL",
    "Left anterior fascicular block": "Hémibloc antérieur gauche",
    "Right axis deviation": "Déviation de l'axe droit",
    "2nd degree AV block - mobitz 1": "Bloc auriculo-ventriculaire du deuxième degré - Mobitz 1",
    "ST depression (inferior - II, III, aVF)": "Dépression du segment ST dans les dérivations inférieures (II, III, aVF)",
    "Acute pericarditis": "Péricardite aiguë",
    "ST elevation (inferior - II, III, aVF)": "Élévation du segment ST dans les dérivations inférieures (II, III, aVF)",
    "Low voltage": "Complexes QRS à bas voltage",
    "Regularly irregular": "Rythme régulièrement irrégulier",
    "Junctional rhythm": "Rythme jonctionnel",
    "Left atrial enlargement": "Hypertrophie atriale gauche",
    "ST elevation (lateral - I, aVL, V5-V6)": "Élévation du segment ST dans les dérivations latérales (I, aVL, V5-V6)",
    "Atrial paced": "Pacemaker auriculaire avec rythme auriculaire électro-entraîné",
    "Right ventricular hypertrophy": "Hypertrophie ventriculaire droite",
    "Delta wave": "Onde delta",
    "Wolff-Parkinson-White (Pre-excitation syndrome)": "Syndrome de Wolff-Parkinson-White (pré-excitation)",
    "Prolonged QT": "QT prolongé",
    "ST depression (anterior - V3-V4)": "Dépression du segment ST dans les dérivations antérieures (V3-V4)",
    "QRS complex negative in III": "Complexe QRS négatif dans la dérivation III",
    "Q wave (lateral- I, aVL, V5-V6)": "Onde Q dans les dérivations latérales (I, aVL, V5-V6)",
    "Supraventricular tachycardia": "Tachycardie supraventriculaire",
    "ST downslopping": "Inclinaison descendante du segment ST",
    "ST depression (lateral - I, avL, V5-V6)": "Dépression du segment ST dans les dérivations latérales (I, avL, V5-V6)",
    "2nd degree AV block - mobitz 2": "Bloc auriculo-ventriculaire du deuxième degré - Mobitz 2",
    "U wave": "Onde U",
    "R/S ratio in V1-V2 >1": "Rapport R/S dans les dérivations V1-V2 > 1",
    "RV1 + SV6\xa0> 11 mm": "RV1 + SV6 supérieur à 11 mm",
    "Left posterior fascicular block": "Hémibloc postérieur gauche",
    "Right atrial enlargement": "Hypertrophie atriale droite",
    "ST depression (septal- V1-V2)": "Dépression du segment ST dans les dérivations septales (V1-V2)",
    "Q wave (septal- V1-V2)": "Onde Q dans les dérivations septales (V1-V2)",
    "Q wave (anterior - V3-V4)": "Onde Q dans les dérivations antérieures (V3-V4)",
    "ST upslopping": "Inclinaison ascendante du segment ST",
    "Right superior axis": "Axe supérieur droit",
    "Ventricular tachycardia": "Tachycardie ventriculaire",
    "ST elevation (posterior - V7-V8-V9)": "Élévation du segment ST dans les dérivations postérieures (V7-V8-V9)",
    "Ectopic atrial rhythm (< 100 BPM)": "Rythme auriculaire ectopique (< 100 BPM)",
    "Lead misplacement": "Inversion des électrodes",
    "Third Degree AV Block": "Bloc auriculo-ventriculaire complet (3ème degré)",
    "Acute MI": "Infarctus du myocarde aigu",
    "Early repolarization": "Repolarisation précoce",
    "Q wave (posterior - V7-V9)": "Onde Q dans les dérivations postérieures (V7-V9)",
    "Bi-atrial enlargement": "Hypertrophie bi-atriale",
    "LV pacing": "Stimulation ventriculaire gauche",
    "Brugada": "Syndrome de Brugada",
    "Ventricular Rhythm": "Rythme ventriculaire",
    "no_qrs": "Pas de segment QRS"
}

