# pipeline project
pipeline_project: !!str "ECG_tokenizer_LLM_finetuning"
runner_name: !!str "LLM_finetuning_runner"
# training parameters
lr: !!float 5e-5
seed: !!int 42
num_workers: !!int 12
num_epochs: !!int 5
weight_decay: !!float 1e-4
batch_size: !!int 32
criterion: !!str "focal_loss"
base_checkpoint_path: !!str "checkpoints"
optimizer: !!str "AdamW"
scheduler_type: !!str "step"
step_size: !!int 1
gamma: !!float 0.1
run_mode: !!str "train"
# tokenizer parameters
tokenizer_name: !!str "gpt2"
max_token_length: !!int 512
# model parameters
huggingface_model_name: !!str "gpt2"
trainable_model_name: !!str "GPT2_WithEmbedding"
embedding_reducer_name: !!str "GPT2_LinearReducer"
gpt2_embedding_size: !!int 768
reducer_dropout: !!float 0.2
# metrics
metrics:
  - !!str "rouge"
  - !!str "bleu"
  - !!str "meteor"
# data parameters
# train_dataset_path: !!str "/media/data1/datasets/DeepECG/SSL_pretraining/split/MIMIC/mimic_v4_clean_train.parquet"
train_dataset_path: !!str "parquets/mimic_v4_clean_train_quarter.parquet"
# validation_dataset_path: !!str "/media/data1/datasets/DeepECG/SSL_pretraining/split/MIMIC/mimic_v4_clean_val.parquet"
validation_dataset_path: !!str "parquets/mimic_v4_clean_val_quarter.parquet"
train_embeddings_path: !!str "/media/data1/datasets/ECG_Tokenizer/embeddings/QINCo_512_mimic_mhi_code15_seq_2500/train"
validation_embeddings_path: !!str "/media/data1/datasets/ECG_Tokenizer/embeddings/QINCo_512_mimic_mhi_code15_seq_2500/test"
output_dir: !!str "checkpoints/gpt2/quarter"
checkpoint_dir: !!str "checkpoints/gpt2/quarter/best_model.pt"
# wandb parameters
wandb_project: !!str "ECG_tokenizer_LLM_finetuning"
wandb_entity: !!str "jacques-delfrate"
use_wandb: !!bool false
