# pipeline project
pipeline_project: !!str "ECG_tokenizer_LLM_finetuning"
runner_name: !!str "LLM_finetuning_runner"
run_mode: !!str "train"
num_epochs: !!int 1
seed: !!int 42
base_checkpoint_path: !!str "checkpoints"
# wandb parameters
wandb_project: !!str "ECG_tokenizer_LLM_finetuning_MHI"
wandb_entity: !!str "mhi_ai"
use_wandb: !!bool true
# training parameters
lr: !!float 5e-5
num_workers: !!int 12
weight_decay: !!float 1e-4
batch_size: !!int 32
criterion: !!str "focal_loss"
optimizer: !!str "AdamW"
scheduler_type: !!str "step"
step_size: !!int 1
gamma: !!float 0.1
# tokenizer parameters
tokenizer_name: !!str "gpt2"
max_token_length: !!int 512
# model parameters
huggingface_model_name: !!str "gpt2"
trainable_model_name: !!str "GPT2_WithEmbedding"
embedding_reducer_name: !!str "GPT2_LinearReducer"
gpt2_embedding_size: !!int 768
reducer_dropout: !!float 0.2
# metrics
metrics:
  - !!str "rouge"
  - !!str "bleu"
  - !!str "meteor"
# data parameters
# train_dataset_path: !!str "/media/data1/datasets/DeepECG/SSL_pretraining/split/MIMIC/mimic_v4_clean_train.parquet"
train_dataset_path: !!str "parquets/mhi/train_trial_v1.1_with_report_en_filtered.parquet"
# validation_dataset_path: !!str "/media/data1/datasets/DeepECG/SSL_pretraining/split/MIMIC/mimic_v4_clean_val.parquet"
validation_dataset_path: !!str "parquets/mhi/test_trial_v1.1_subset_with_report_en_filtered.parquet"
train_embeddings_path: !!str "embeddings/mhi/train"
validation_embeddings_path: !!str "embeddings/mhi/test"
checkpoint_dir: !!str "checkpoints/gpt2/mimic_mhi/best_model.pt"
# Inference parameters
inference_dataset_path: !!str "parquets/mhi/test_trial_v1.1_with_report.parquet"
output_dir: !!str "checkpoints/gpt2/mimic_mhi/mhi_inference"
