command:
  - python
  - ./linear_probe.py
  - "--base_config"
  - "config/linear_probing/base_config.yaml"
  - ${args}

method: bayes

name: "final_sweep"
project: "ECG_Tokenizer_Linear_Probing"
entity: "jacques-delfrate"

metric:
  name: validate/cls_loss
  goal: minimize

parameters:
  lr:
    values: [1e-6, 1e-5, 1e-4, 1e-3]

  batch_size:
    values: [16, 32]

  weight_decay:
    values: [1e-4, 1e-3, 1e-2]

  criterion:
    values: ["focal_loss", "bce_loss"]

  num_layers:
    values: [1, 2, 3]

  hidden_dim:
    values: [256, 512, 1024, 2048]
  name:
    values: ["sweep"]
  project:
    values: ["ECG_Tokenizer_Linear_Probing"]
  entity:
    values: ["jacques-delfrate"]

early_terminate:
  type: hyperband
  min_iter: 3
  eta: 2
  s: 2



  